/**
 * 증권거래소 도메인 이벤트(설계서 §4.9 Phase 1).
 *
 * **시장이 자기 이벤트 종류를 소유한다.** `game/events.js`의 `EVENT_TYPES`가 이 목록을 펼쳐 담아
 * 클라이언트에게는 여전히 한 장의 카탈로그로 보인다 — 새 서브시스템이 붙을 때 게임 쪽 파일을
 * 고치지 않고 자기 목록만 만들면 되게 하기 위한 방향이다.
 *
 * 각 이벤트의 정확한 필드는 `docs/API.md` 7장에 있다.
 */
export const MARKET_EVENT_TYPES = Object.freeze({
  // 거래 창구
  TRADING_OPENED: 'TRADING_OPENED',
  TRADING_CLOSED: 'TRADING_CLOSED',
  ORDER_FILLED: 'ORDER_FILLED',
  DEPOSIT_MADE: 'DEPOSIT_MADE',
  DEPOSIT_WITHDRAWN: 'DEPOSIT_WITHDRAWN',
  DEPOSIT_INTEREST_PAID: 'DEPOSIT_INTEREST_PAID',
  DIVIDEND_PAID: 'DIVIDEND_PAID',

  // 라운드 틱(순서: CYCLE_CHANGED? → NEWS_PUBLISHED → BASE_RATE_CHANGED? → PRICES_UPDATED
  //           → INSTRUMENT_DELISTED?/HOLDINGS_WIPED? → INSTRUMENT_LISTED? → DEPOSIT_INTEREST_PAID?)
  CYCLE_CHANGED: 'CYCLE_CHANGED',
  NEWS_PUBLISHED: 'NEWS_PUBLISHED',
  BASE_RATE_CHANGED: 'BASE_RATE_CHANGED',
  PRICES_UPDATED: 'PRICES_UPDATED',
  INSTRUMENT_DELISTED: 'INSTRUMENT_DELISTED',
  INSTRUMENT_LISTED: 'INSTRUMENT_LISTED',
  HOLDINGS_WIPED: 'HOLDINGS_WIPED',

  // 예약 주문
  QUEUED_ORDER_PLACED: 'QUEUED_ORDER_PLACED',
  QUEUED_ORDER_CANCELLED: 'QUEUED_ORDER_CANCELLED',
  QUEUED_ORDER_EXECUTED: 'QUEUED_ORDER_EXECUTED',
  QUEUED_ORDER_REJECTED: 'QUEUED_ORDER_REJECTED',
});

/** 거래 창구가 닫힌 이유. */
export const TRADING_CLOSE_REASONS = Object.freeze({
  /** 플레이어가 `CLOSE_TRADING`으로 직접 마감했다. */
  PLAYER: 'PLAYER',
  /** 창구 예산(주문 3건)을 다 써서 서버가 자동으로 닫았다. */
  BUDGET_EXHAUSTED: 'BUDGET_EXHAUSTED',
});
