import { PHASES } from './phases.js';

/** 게임 커맨드 종류. */
export const COMMAND_TYPES = Object.freeze({
  ROLL: 'ROLL',
  BUY: 'BUY',
  SKIP_BUY: 'SKIP_BUY',
  BUILD: 'BUILD',
  SKIP_BUILD: 'SKIP_BUILD',
  CASINO_BET: 'CASINO_BET',
  CASINO_LEAVE: 'CASINO_LEAVE',
  ISLAND_PAY: 'ISLAND_PAY',
  ISLAND_ROLL: 'ISLAND_ROLL',
  TRAVEL: 'TRAVEL',
  SELL: 'SELL',
});

export const ALL_COMMAND_TYPES = Object.freeze(Object.values(COMMAND_TYPES));

/** 커맨드별 허용 페이즈(단일 출처). */
export const COMMAND_PHASES = Object.freeze({
  [COMMAND_TYPES.ROLL]: [PHASES.AWAIT_ROLL],
  [COMMAND_TYPES.BUY]: [PHASES.AWAIT_BUY],
  [COMMAND_TYPES.SKIP_BUY]: [PHASES.AWAIT_BUY],
  [COMMAND_TYPES.BUILD]: [PHASES.AWAIT_BUILD],
  [COMMAND_TYPES.SKIP_BUILD]: [PHASES.AWAIT_BUILD],
  [COMMAND_TYPES.CASINO_BET]: [PHASES.AWAIT_CASINO],
  [COMMAND_TYPES.CASINO_LEAVE]: [PHASES.AWAIT_CASINO],
  [COMMAND_TYPES.ISLAND_PAY]: [PHASES.AWAIT_ISLAND_CHOICE],
  [COMMAND_TYPES.ISLAND_ROLL]: [PHASES.AWAIT_ISLAND_CHOICE],
  [COMMAND_TYPES.TRAVEL]: [PHASES.AWAIT_TRAVEL],
  [COMMAND_TYPES.SELL]: [PHASES.AWAIT_LIQUIDATION],
});
