import { PHASES } from './phases.js';

/** 게임 커맨드 종류. */
export const COMMAND_TYPES = Object.freeze({
  ROLL: 'ROLL',
  BUY: 'BUY',
  SKIP_BUY: 'SKIP_BUY',
  BUILD: 'BUILD',
  SKIP_BUILD: 'SKIP_BUILD',
  START_BUILD: 'START_BUILD',
  SKIP_START_BUILD: 'SKIP_START_BUILD',
  ACQUIRE: 'ACQUIRE',
  SKIP_ACQUIRE: 'SKIP_ACQUIRE',
  CASINO_BET: 'CASINO_BET',
  CASINO_LEAVE: 'CASINO_LEAVE',
  ISLAND_PAY: 'ISLAND_PAY',
  ISLAND_ROLL: 'ISLAND_ROLL',
  TRAVEL: 'TRAVEL',
  SELL: 'SELL',
  AUTO_SELL: 'AUTO_SELL',
  TAKE_LOAN: 'TAKE_LOAN',
  DECLARE_BANKRUPTCY: 'DECLARE_BANKRUPTCY',
});

export const ALL_COMMAND_TYPES = Object.freeze(Object.values(COMMAND_TYPES));

/**
 * 커맨드를 보낼 수 있는 **행동 주체**의 종류.
 *
 * 지금은 한 가지뿐이지만, 앞으로 "현재 턴 플레이어가 아닌 행동 주체"가 생긴다
 * (예: 압류 경매의 입찰자 좌석). 그때 상태기계를 흔들지 않도록 골격을 미리 둔다 —
 * 검증은 `COMMAND_PHASES`(어떤 페이즈인가)와 이 표(누가 보낼 수 있는가)의 이중 검사다.
 */
export const COMMAND_OWNERSHIPS = Object.freeze({
  /** 지금 차례인 좌석만 보낼 수 있다. */
  CURRENT_PLAYER: 'CURRENT_PLAYER',
});

/** 커맨드별 행동 주체(단일 출처). 지금은 전부 현재 턴 플레이어다. */
export const COMMAND_OWNERSHIP = Object.freeze(
  Object.fromEntries(
    ALL_COMMAND_TYPES.map((type) => [type, COMMAND_OWNERSHIPS.CURRENT_PLAYER]),
  ),
);

/** 커맨드별 허용 페이즈(단일 출처). */
export const COMMAND_PHASES = Object.freeze({
  [COMMAND_TYPES.ROLL]: [PHASES.AWAIT_ROLL],
  [COMMAND_TYPES.BUY]: [PHASES.AWAIT_BUY],
  [COMMAND_TYPES.SKIP_BUY]: [PHASES.AWAIT_BUY],
  [COMMAND_TYPES.BUILD]: [PHASES.AWAIT_BUILD],
  [COMMAND_TYPES.SKIP_BUILD]: [PHASES.AWAIT_BUILD],
  [COMMAND_TYPES.START_BUILD]: [PHASES.AWAIT_START_BUILD],
  [COMMAND_TYPES.SKIP_START_BUILD]: [PHASES.AWAIT_START_BUILD],
  [COMMAND_TYPES.ACQUIRE]: [PHASES.AWAIT_ACQUIRE],
  [COMMAND_TYPES.SKIP_ACQUIRE]: [PHASES.AWAIT_ACQUIRE],
  [COMMAND_TYPES.CASINO_BET]: [PHASES.AWAIT_CASINO],
  [COMMAND_TYPES.CASINO_LEAVE]: [PHASES.AWAIT_CASINO],
  [COMMAND_TYPES.ISLAND_PAY]: [PHASES.AWAIT_ISLAND_CHOICE],
  [COMMAND_TYPES.ISLAND_ROLL]: [PHASES.AWAIT_ISLAND_CHOICE],
  [COMMAND_TYPES.TRAVEL]: [PHASES.AWAIT_TRAVEL],
  [COMMAND_TYPES.SELL]: [PHASES.AWAIT_LIQUIDATION],
  [COMMAND_TYPES.AUTO_SELL]: [PHASES.AWAIT_LIQUIDATION],
  [COMMAND_TYPES.TAKE_LOAN]: [PHASES.AWAIT_LIQUIDATION],
  [COMMAND_TYPES.DECLARE_BANKRUPTCY]: [PHASES.AWAIT_LIQUIDATION],
});
