import { MARKET_EVENT_TYPES } from '../market/events.js';

/**
 * 도메인 이벤트 종류. 커맨드 처리 결과로 발생하며 UI 로그/연출의 입력이 된다.
 * 각 이벤트의 필드는 docs/API.md에 문서화되어 있다.
 *
 * 서브시스템은 **자기 이벤트 목록을 스스로 소유**하고 여기서 펼쳐 담긴다(`market/events.js`).
 * 그래서 새 서브시스템이 붙어도 이 파일은 한 줄만 늘어나고, 클라이언트에게는 여전히
 * 한 장의 카탈로그로 보인다.
 */
export const EVENT_TYPES = Object.freeze({
  TURN_STARTED: 'TURN_STARTED',
  DICE_ROLLED: 'DICE_ROLLED',
  MOVED: 'MOVED',
  LAP_ADVANCED: 'LAP_ADVANCED',
  SALARY_PAID: 'SALARY_PAID',
  LANDED: 'LANDED',
  CITY_PURCHASED: 'CITY_PURCHASED',
  PURCHASE_DECLINED: 'PURCHASE_DECLINED',
  BUILD_OFFERED: 'BUILD_OFFERED',
  BUILT: 'BUILT',
  LANDMARK_BUILT: 'LANDMARK_BUILT',
  BUILD_DECLINED: 'BUILD_DECLINED',
  START_BONUS_OFFERED: 'START_BONUS_OFFERED',
  ACQUIRE_OFFERED: 'ACQUIRE_OFFERED',
  ACQUIRED: 'ACQUIRED',
  ACQUIRE_DECLINED: 'ACQUIRE_DECLINED',
  TOLL_PAID: 'TOLL_PAID',
  TAX_PAID: 'TAX_PAID',
  TICKET_DRAWN: 'TICKET_DRAWN',
  MONEY_GAINED: 'MONEY_GAINED',
  MONEY_LOST: 'MONEY_LOST',
  MONEY_TRANSFERRED: 'MONEY_TRANSFERRED',
  STRANDED: 'STRANDED',
  ISLAND_RESCUE_PAID: 'ISLAND_RESCUE_PAID',
  ISLAND_ESCAPED: 'ISLAND_ESCAPED',
  ISLAND_STAY: 'ISLAND_STAY',
  CASINO_ENTERED: 'CASINO_ENTERED',
  CASINO_RESULT: 'CASINO_RESULT',
  CASINO_LEFT: 'CASINO_LEFT',
  JACKPOT_CHANGED: 'JACKPOT_CHANGED',
  AIRPORT_TICKET_GRANTED: 'AIRPORT_TICKET_GRANTED',
  AIRPORT_READY: 'AIRPORT_READY',
  TRAVELED: 'TRAVELED',
  LIQUIDATION_REQUIRED: 'LIQUIDATION_REQUIRED',
  PROPERTY_SOLD: 'PROPERTY_SOLD',
  DEBT_SETTLED: 'DEBT_SETTLED',
  LOAN_TAKEN: 'LOAN_TAKEN',
  LOAN_REPAID: 'LOAN_REPAID',
  SALARY_SEIZED: 'SALARY_SEIZED',
  BANKRUPT: 'BANKRUPT',
  EXTRA_TURN: 'EXTRA_TURN',
  TURN_ENDED: 'TURN_ENDED',
  ROUND_ADVANCED: 'ROUND_ADVANCED',
  GAME_OVER: 'GAME_OVER',
  // 증권거래소(투자 모드 STOCKS) — 목록의 주인은 `market/events.js`다.
  ...MARKET_EVENT_TYPES,
});

/** 게임 종료 사유. */
export const GAME_OVER_REASONS = Object.freeze({
  LAST_SURVIVOR: 'LAST_SURVIVOR',
  ROUND_LIMIT: 'ROUND_LIMIT',
});

/**
 * 돈 이동 사유(이벤트 필드 `reason`).
 * 정의는 돈 계층(`shared/MoneyIntent.js`)에 있다 — intent·장부 내역·이벤트가 **같은 목록**을
 * 써야 하므로 단일 출처를 돈 계층에 두고 여기서는 이벤트 사용자를 위해 다시 내보낸다.
 */
export { MONEY_REASONS } from '../shared/MoneyIntent.js';
